# https://git-cliff.org/docs/configuration
[bump]
initial_tag = "v0.1.0"
features_always_bump_minor = true
breaking_always_bump_major = true

[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }}
    **{{ timestamp | date(format="%Y-%m-%d") }}**
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | unique(attribute="message") | filter(attribute="merge_commit") | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        + {% if commit.breaking %}**!!** {% endif %}{{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
trim = true
footer = """
"""
postprocessors = [
  # { pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" }, # replace repository URL
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  # { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"}, # replace issue numbers
]
commit_parsers = [
  # increment major version
  { message = "^feat!", group = "<!--0-->Breaking Changes" },
  # increment minor version
  { message = "^feat.*: add", group = "<!--1-->New Features" },
  { message = "^feat.*: deprecate", group = "<!--2-->Deprecated Features" },
  { message = "^feat.*", group = "<!--3-->Updated Features" },
  # increment patch version
  { message = "^build", group = "<!--5-->Build Artefacts" },
  { message = "^cicd", group = "<!--5-->Pipeline Artefacts" },
  { message = "^defect", group = "<!--4-->Corrected Defects" },
  { message = "^dep", group = "<!--5-->Dependencies" },
  { message = "^perf", group = "<!--6-->Performance Enhancements"},
  { message = "^sec", group = "<!--6-->Security Enhancements"},
  # no increment
  { message = "^doc", group = "Documentation" },
  { message = "^meta", group = "Meta Artefacts" },
  { message = "^refactor", group = "Refactored Features" },
  { message = "^style", group = "Stylistic & Idiomatic Enhancements" },
  { message = "^test", group = "Test Artefacts" },
  # ignore
  { message = "^chore", skip = true },
  { message = "^merge", skip = true },
  { message = "^wip", skip = true },
]
protect_breaking_commits = true
filter_commits = true
# tag_pattern = "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
tag_pattern = "^v[0-9]+\\.[0-9]+\\.[0-9]+(-(alpha|beta)\\.[1-9]+[0-9]*$)?"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
